#!/usr/bin/env python3
"""Writes the engine's LoRA key tables (Engine/Sources/TurboEngineCore/LoRA/LoRAMappingTables.swift)
from mflux's own mappings, so a LoRA file reaches the same layers in the engine as in mflux.

mflux lists, for every layer a LoRA can adapt, each spelling of its keys it accepts: prefixes
(`diffusion_model.`, `transformer.`, `base_model.model.`), the names of the two matrices (`lora_A`,
`lora_down`, `lora.down`, with or without `.default` and `.weight`) and Kohya's underscored form.
The engine strips those the same way before it looks a key up (`LoRAMapping.canonical`), so the
tables keep one entry per layer and spelling of its path: the source path, with `{block}` for the
block number, the module path it adapts, and how the up matrix is cut when one source matrix
feeds three layers (BFL's fused `qkv`, split in thirds as mflux's `split_q_up` and friends do).

Run it with a Python that has mflux (Engine/Fixtures/requirements.txt):
  $PY Engine/Fixtures/export_lora_mappings.py
"""

import sys
from importlib.metadata import version
from pathlib import Path

from mflux.models.flux2.weights.flux2_lora_mapping import Flux2LoRAMapping
from mflux.models.qwen.weights.qwen_lora_mapping import QwenLoRAMapping
from mflux.models.z_image.weights.z_image_lora_mapping import ZImageLoRAMapping

OUT = Path(__file__).resolve().parents[1] / "Sources/TurboEngineCore/LoRA/LoRAMappingTables.swift"

# The tables by the engine's name for them (`LoRAMapping.Table`).
MAPPINGS = {
    "zImage": ZImageLoRAMapping,
    "flux2": Flux2LoRAMapping,
    "qwen": QwenLoRAMapping,
}

# Kept in step with LoRAMapping.canonical in the engine.
PREFIXES = ["base_model.model.", "model.diffusion_model.", "diffusion_model.", "transformer."]
MATRIX_SUFFIXES = [
    f".{name}{default}{weight}"
    for name in ("lora_A", "lora_B", "lora_down", "lora_up", "lora.down", "lora.up")
    for default in (".default", "")
    for weight in (".weight", "")
] + [".alpha"]
# Kohya's and LyCORIS's spellings: the path with underscores for its dots, after this prefix.
UNDERSCORED = ("lora_unet_", "lycoris_")

SPLITS = {
    None: "none",
    "split_q_up": "q",
    "split_k_up": "k",
    "split_v_up": "v",
}
IDENTITY_DOWNS = {None, "split_q_down", "split_k_down", "split_v_down"}


def canonical(pattern: str) -> str:
    """The path a key names, without its prefixes and matrix suffix (an underscored one keeps its
    `lora_unet_` or `lycoris_`)."""
    for suffix in MATRIX_SUFFIXES:
        if pattern.endswith(suffix):
            pattern = pattern[: -len(suffix)]
            break
    else:
        raise ValueError(f"no matrix suffix in {pattern}")
    stripped = True
    while stripped:
        stripped = False
        for prefix in PREFIXES:
            if pattern.startswith(prefix):
                pattern = pattern[len(prefix):]
                stripped = True
    return pattern


def underscored(source: str) -> bool:
    return source.startswith(UNDERSCORED)


def spells(source: str, path: str) -> bool:
    """Whether an underscored source is the dotted `path` with underscores."""
    return any(source == prefix + path.replace(".", "_") for prefix in UNDERSCORED)


def rows(mapping) -> list[tuple[str, str, str]]:
    rows: dict[tuple[str, str], str] = {}
    for target in mapping.get_mapping():
        up = target.up_transform.__name__ if target.up_transform else None
        down = target.down_transform.__name__ if target.down_transform else None
        if up not in SPLITS:
            raise ValueError(f"{target.model_path}: the engine has no {up}")
        if down not in IDENTITY_DOWNS:
            raise ValueError(f"{target.model_path}: the engine has no {down}")
        sources = {canonical(p) for p in target.possible_up_patterns + target.possible_down_patterns + target.possible_alpha_patterns}
        dotted = {s for s in sources if not underscored(s)}
        for source in sorted(sources):
            # An underscored spelling of a dotted path already listed needs no row: the engine
            # looks underscored keys up through the dotted rows' underscored form.
            if underscored(source) and any(spells(source, d) for d in dotted):
                continue
            if source.count("{block}") > 1 or target.model_path.count("{block}") > 1:
                raise ValueError(f"{source} → {target.model_path}: more than one block number")
            key = (source, target.model_path)
            if rows.get(key, SPLITS[up]) != SPLITS[up]:
                raise ValueError(f"{source} → {target.model_path} is cut two ways")
            rows[key] = SPLITS[up]
    return [(source, path, split) for (source, path), split in sorted(rows.items())]


def main() -> None:
    lines = [
        f"// Generated by Engine/Fixtures/export_lora_mappings.py from mflux {version('mflux')}'s LoRA mappings: do not edit.",
        "",
        "extension LoRAMapping {",
        "    /// Source path (prefixes and matrix suffix stripped, `{block}` for the block number) → the",
        "    /// module path it adapts, and how the up matrix is cut for it.",
    ]
    for name, mapping in MAPPINGS.items():
        table = rows(mapping)
        lines.append(f"    static let {name}Rows: [Row] = [")
        for source, path, split in table:
            lines.append(f'        Row("{source}", "{path}", .{split}),')
        lines.append("    ]")
        print(f"{name}: {len(table)} rows")
    lines.append("}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"written to {OUT}")


if __name__ == "__main__":
    sys.exit(main())
